apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-sa
  namespace: todoapp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: todoapp
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-reader
  namespace: todoapp
subjects:
- kind: ServiceAccount
  name: todo-sa
  namespace: todoapp
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io